//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureLabelReprint_ByPart_WebApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=USAZ1DTB002P;Initial Catalog=EpicorERP;Persist Security Info=True;Use" +
            "r ID=\'ErpAdmin\';Password=\'@cggjK0818\'")]
        public string DBConnectionLive {
            get {
                return ((string)(this["DBConnectionLive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=USAZ1DTB002P;Initial Catalog=EpicorERPTest;Persist Security Info=True" +
            ";User ID=\'ErpAdmin\';Password=\'@cggjK0818\'")]
        public string DBConnectionTest {
            get {
                return ((string)(this["DBConnectionTest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=USAZ1DTB002P;Initial Catalog=EpicorERPPilot;Persist Security Info=Tru" +
            "e;User ID=\'ErpAdmin\';Password=\'@cggjK0818\'")]
        public string DBConnectionPilot {
            get {
                return ((string)(this["DBConnectionPilot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EpicorERPTest")]
        public string TestServerID {
            get {
                return ((string)(this["TestServerID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EpicorERPPilot")]
        public string PilotServerID {
            get {
                return ((string)(this["PilotServerID"]));
            }
        }
    }
}
